restic/rest-server

handlers.go
main.go

Legacy code which created repo on first "POST /keys/foo" remains, so
restic clients <= v0.3.3 continue working.

Implement POST /path?create=true for explicit repository creation

---

docker/entry.sh

Example:
`docker run -e OPTIONS="--append-only" restic/rest-server`

Allow the $OPTIONS env var when using docker image

---

htpasswd.go

If htpasswd was modified, it will be automatically reloaded.
This check happens at most once per second and only on incoming requests.
Note that this removes the public `NewHtpasswd()` function.

Automatically reload htpasswd

---

cmd/rest-server/main.go

I don't know go, but it seems to me that the `--prometheus` flag wasn't checked instead `--append-only` enabled the prometheus metric behaviour.

fix prometheus config flag

---

examples/bsd/freebsd
examples/bsd/openbsd

The OpenBSD rc script will be packaged with the [rest-server](https://github.com/jasperla/openbsd-wip/blob/master/sysutils/rest-server/pkg/rest_server.rc) port once it is imported (hopefully this week).

add example rc scripts for OpenBSD and FreeBSD

---

.travis.yml
build.go

The problem is that in Go < 1.9 "..." also matches the vendor directory,
and we don't want to run those tests :)

Travis: Fix tests (again)

---

README.md
cmd/rest-server/main.go
mux.go

This change moves version output to a dedicated `--version`/`-V` option, which is more conventional and in line with both restic and rclone.
For now it's done with a regular flag, but once there's a new version of spf13/cobra we can use Cobra's built-in support for `--version` (the code for this is included in this commit, but commented out).

Add --version flag to print version and exit.

---

README.md

I noticed that if there's no `.htpasswd` file, rest-server is wide open to back up to by anyone who can access it. This is highly easy to miss and not know about!
This PR adds a little text to help clarify that somewhat, so it's not entirely unnoticed when reading the README file.

Clarify that authentication does NOT happen without a .htpasswd file.

---

README.md
cmd/rest-server/main.go
cmd/rest-server/main_test.go
mux.go

In order to prevent users from accidentally exposing rest-server without
authentication, rest-server now defaults to requiring a .htpasswd. If
you want to disable authentication, you need to explicitly pass the new
--no-auth flag.
Closes #60

Require auth by default, add --no-auth flag

---

changelog/unreleased/pull-64
handlers.go
handlers_test.go

While working on the `rclone serve restic` command I noticed that is currently possible to overwrite the config file in a repo even if `--append-only` is specified. The first commit adds proper tests, and the second commit fixes the issue.

Security: Refuse overwriting the config file in append-only mode

---

cmd/rest-server/main.go
cmd/rest-server/main_test.go
handlers.go
handlers_test.go
mux.go

I know this diff looks huge, but it's actually pretty simple: instead of a global value named `Config`, the identifier named `Config` is now a `struct` type. Instead of having all sorts of global configuration, we confine it to that struct... and attach the handlers as methods on the struct.
It's a lot cleaner, in that CLI options are confined to `main` and the main() function just builds a `Config` struct like any other user of the library would.
This makes it possible to use the `restserver` package as a library.
The default configuration is still preserved.
Closes #66
/cc @rawtaz

Refactor handlers: make Config not global

---

cmd/rest-server/main.go
handlers.go
maxsizewriter.go
mux.go

The --max-size limits the number of bytes that can be stored to a repo. It only takes effect on SaveBlob.
Closes https://github.com/restic/rest-server/issues/65
Can see previous discussion at https://github.com/mholt/rest-server/pull/1
/cc @dotlambda

Add --max-size flag to limit size of repositories

---

examples/systemd/rest-server.service

The directive "StartLimitInterval" has been replaced by [StartLimitIntervalSec=interval, StartLimitBurst=burst](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=interval). I'd suggest that the default backoff settings are fine (in Ubuntu 19.10 no more than 5 restarts per 10 seconds, else delayed by 10 seconds per attempt) so this directive can simply be removed.
No, tiny change so assumed not necessary.
Checklist
---------

Tweak systemd unit file

---

examples/systemd/rest-server.service

In addition to any existing filesystem restrictions on the (www-data)
backup user these config options uses namespaces and other kernel
features to further restrict what the _rest-server_ is allowed to do.
* `ProtectSystem=strict` and `ReadWritePaths=/path/to/backups` ensures
that the _rest-server_ is only allowed to write to its data directory.
* `ProtectHome=yes` and `PrivateTmp=yes` limits what the _rest-server_
gets (read) access to.
* `NoNewPrivileges=yes` prevents the _rest-server_ from using setuid
binaries, etc to escalate its privileges.
See https://www.freedesktop.org/software/systemd/man/systemd.exec.html
for further details
While at I also replaced the …

Make example systemd service more restrictive

---

changelog/unreleased/issue-131
htpasswd.go

"/" is valid char in HTTP authorization headers, but are also used in
rest-server to map usernames to private repos.
This commit prevents loading maliciously composed usernames like
"/foo/config".
Issue: #131 
Checklist
---------

Security: Prevent loading of usernames containing a slash

---

changelog/unreleased/issue-131
htpasswd.go

TODO: Once PR #112 is merged, change this to used folderPathValid(), but let's merge this fix first.
PR #132 added constraints on htpasswd usernames. As described in #134, this unintentionally disallows numbers.
Closes #134 
Checklist
---------

Allow numbers in htpasswd usernames

---

Dockerfile
README.md
changelog/unreleased/issue-146

Using docker's multi-stage builds we can build the restic/rest-server
within a golang build environment then create a container for use
(without the build environment) in a second build stage.
The advantages are:
1. Building the rest-server is predictable in a pristine environment
each time.
2. Container builds ensure we get the latest rest-server every time.
~~Not yet - will create an issue now.~~
https://github.com/restic/rest-server/issues/146
Checklist
---------
NOTE: I will go through this checklist as soon as possible to satisfy all the requirements.

Build restic at container build time

---

changelog/unreleased/issue-122
cmd/rest-server/main.go
handlers.go
handlers_test.go
repo/repo.go

The restic uses the sha256 hash to calculate filenames based on the file content. Check on the rest-server side that the uploaded file is intact and reject it otherwise.
This PR complements https://github.com/restic/restic/pull/3178 . However, this PR does not depend on the mentioned restic PR and should work with every restic version.
Fixes #122
Checklist
---------

Verify uploaded files

---

cmd/rest-server/main.go

The rest server is normally shutdown via a SIGINT signal. The http handle calls are endless loops and don't return in the normal case. Thus add a signal handler to shutdown the profiler.
This prevents loosing the latest parts of the profiling log.
No.
Checklist
---------
- ~~[ ] I have added tests for all changes in this PR~~
- ~~[ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/chang …

Properly close CPU profile on SIGINT

---

README.md

It updates the tutorial for creating self-signed certificates. Without this change restic 0.12.0 compiled with go1.15.8 on windows/amd64 will fail to connect to your restic server, even with `--cacert` option. Error messages are, depending on what entered at `Common name` in the openssl dialog:
Entering nothing or `*`: `x509: certificate is not valid for any names, but wanted to match yourdomain.com`
Entering `yourdomain.com`: `x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0` …

Updated self-signed certificate creation

---

changelog/unreleased/pull-142
handlers_test.go
repo/repo.go

This PR implements atomic uploads for blobs and also ensures that the directory entry for the blob is durably stored on disk.
Together with #130 this guarantees that uploaded blobs which are stored under their real filename are correct. Incomplete uploads or server crashes can at most cause the existence of incomplete temporary files.
The atomic uploads also solve a possible race condition during uploads, which can lead to missing pack files. That scenario could occur when the first upload fails partway and the server doesn't notice that immediately. A later retry by restic will then delete the broken upload and upload the file again. If the server now notices that the initial …

Atomic file upload and directory sync

---

changelog/unreleased/issue-126
cmd/rest-server/listener_unix.go
cmd/rest-server/listener_windows.go
cmd/rest-server/main.go
examples/systemd/rest-server.service
examples/systemd/rest-server.socket
go.mod
go.sum

This change allows `rest-server` to be run on demand by systemd (socket activation). The rationale for supporting both is as follows:
1. On demand running with a listening socket opened externally is a good idea because then `rest-server` does not have to have the privileges to listen on a port.
2. My first choice for that would be systemd (so the process can even be restricted further), but it is not available for non-Linux systems
Closes #126 
Supersedes #127
Checklist
---------

Support running on demand via systemd

---

docker/create_user

The create_users script should use bcrypt when hashing the password for new users. This was missed when adding bcrypt support in rest-server 0.9.7.
Fixes #141.
Checklist
---------

docker: use bcrypt in create_users script

---

go.mod
go.sum
handlers_test.go
repo/repo.go

This switches the SHA256 verification to Minios optimized library. This results in improved throughput for many processors.
This is the same library that is also used in Restic (see https://github.com/restic/restic/pull/2709 )
Shortly as remark in https://github.com/restic/rest-server/pull/130 where the verification of uploaded files was introduced. 
Checklist
---------
* ~~I have added tests for all changes in this PR~~
* ~~I have added documentation for the changes (in the manual)~~
* ~~There's a new file in `changelog/unreleased/` that describes the …

Use Minio's optimized SHA-256

---

cmd/rest-server/main.go

This change addresses an issue in which the value of the `--prometheus-no-auth` flag actually got applied to the value of `--prometheus` when reading in flags.
Issue was introduced in #112 alongside the inital implementation for `--prometheus-no-auth`
Checklist
---------

Config: Read in PrometheusNoAuth correctly

---

changelog/unreleased/pull-160
handlers_test.go
quota/quota.go
repo/repo.go

This pull request will change the current behavior on disk-related errors:
* HTTP 507 "Insufficient storage" is the status on disk full or over-quota
* HTTP 500 "Internal server error" on other disk-related errors
Previously both were 400 "Bad request"
Issue: https://github.com/restic/rest-server/issues/155
Checklist
---------

Reply "insufficient storage" on disk full or over-quota

---

README.md
changelog/unreleased/pull-158
cmd/rest-server/main.go

This pull request removes the hardcoded reference to `/tmp/restic` replacing with platform-specific path, retrieved using `os.TempDir()` stdlib function.
Issue #157 
Checklist
---------
- I have added tests for all changes in this PR
- No need for test, `os.TempDir()` is a builtin function

Use os.TempDir() for temporary directory in default path

---

README.md

Fixes #128, the two distinct docker sections of the README are merged into one.
Checklist
---------
- ~[ ] I have added tests for all changes in this PR~
- ~[ ] I have added documentation for the changes (in the manual)~
- ~[ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))~
- ~[ ] I have run `gofmt` on the code in all commits~

Clarification of docker section in README.md

---

README.md

Added `-nodes` option for ssl certificate generation. Otherwise a password with at least 4 characters length for the private_key must be given. However there is no option for providing a password for the private_key. It would also add no additional security, because for automatic server startup key file should/must be unencrypted.
Soruce for the new flag: https://serverfault.com/questions/366372/is-it-possible-to-generate-rsa-key-without-pass-phrase
No. Just wanted to generate a new certificate for a new server and struggled.
Checklist
---------

Readme: Fixed SSL certificate generation

---

changelog/unreleased/issue-182
htpasswd.go

Allow usernames containing underscore again, after they were forbidden by #131.
Fixes #182 
Checklist
---------

Allow underscores in usernames

---

cmd/rest-server/main.go

Currently, `--help` says:
...
--listen string        listen address (default ":8000")
--log string           log HTTP requests in the combined log format
--max-size int         the maximum size of the repository in bytes
...
I looked through the documentation and even gave the source code a glance to find what this "string" is supposed to be, which options exist? I just want it to dump the URI or something, whatever the syntax is for that in this combined format, why is an argument even required and can't I use some default?
Some `%s`-like guesses later and not seeing any log messages at all upon doing requests to the server, I moved on and did an `ls` for unrelated reasons, finding that it had created my attempts as filenames. *Aha, it has to be a filename! It doesn't simply log to …

Be more clear in --help what the value of --log is supposed to be

---

README.md
changelog/unreleased/issue-187
cmd/rest-server/main.go
cmd/rest-server/main_test.go
docker/entrypoint.sh
handlers.go
mux.go

Allows users to configure the location of the `.htpasswd` file.
Closes #187 
Checklist
---------

Add configurable htpasswd location

---

changelog/unreleased/issue-133
htpasswd.go
htpasswd_test.go

As shown in #133 checking the basic auth credentials can substantially slow down the rest-server. The discussion there has also weighed the pros and cons of using separate auth tokens or just caching the credentials. This PR implements the latter variant as it is far simpler, and there's no obvious reason why a short-term cache would be a security issue.
The implementation tries to avoid introducing timing side-channels by ensuring that the control flow does not depend on the cached password. There's also an experimental commit which tries to overwrite expired cache entries. …

Cache basic auth credentials

---

changelog/unreleased/pull-194
handlers_test.go
repo/repo.go

When files in a repository cannot be read by rest-server, for example after running `restic prune` directly on the server hosting the repositories, then rest-server returned "Not Found" as status code. This is extremely confusing for users.
The PR fixes the error handling when files cannot be accessed. If the returned error is `fs.ErrNotExist` then it is turned into a "Not Found" status code, all other errors now result in an "Internal Error" together with a debug log output.
Fixes https://github.com/restic/restic/issues/1871
Checklist
---------

Return "internal server error" if files cannot be read

---

repo/repo.go
repo/repo_unix.go
repo/repo_windows.go

Storing a repository on a filesystem that does not support fsync is currently not possible. This PR syncs the ignored fsync errors from the restic backend to also allow storing a repository on these filesystems. However, this is not recommended as without fsync it is not possible to guarantee the integrity of uploaded data.
In addition, macOS Ventura seems to have introduced an additional error code, see #198.
Fixes #198.
Checklist
---------

Ignore fsync errors

---

changelog/unreleased/pull-207
cmd/rest-server/main.go

rest-server doesn't accept arguments. Thus, error out to prevent wrong usage.
Fixes https://github.com/restic/rest-server/issues/206
Checklist
---------

Error out on unexpected command line argument

---

examples/systemd/rest-server.service

Running 32bit on a 64bit host with SystemCallArchitectures will fail without much information
I didn't expect this to require a real issue. It's just me trying to debug a non-start restic-server for 1h, simply because I didn't see an amd64 built was available - github collapses the release artifacts due to the amount - and the "native" setting in the default service unit will create weird crashes.
Effectively you get 0 information, it just crashes with `code=killed, status=31/SYS` (which is true for anything running into filtered system calls).
Add some note about a possibly weird failure of running rest-server with the systemd unit, when trying to run the i386 binary on amd64 …

warn about SystemCallArchitectures in the systemd service

---

examples/compose-with-grafana/dashboards/rest-server.json

Allows to select datasource when first importing into grafana, thus making the dashboard portable.
Don't think this was discussed anywhere
Checklist
---------
- [N/A] I have added tests for all changes in this PR
- [N/A] I have added documentation for the changes (in the manual)
- [N/A] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))
- [N/A] I have run `gofmt` on the code in all commits
- [N/A] All commit messages are formatted in …

Make dashboard portable

---

changelog/unreleased/issue-219
handlers_test.go
repo/repo.go

Listing the data/ folder in a repository no longer fails if it contains files in the data/ folder. This also ignores .DS_Store files created by macOS.
Fixes #219.
Checklist
---------

Ignore unexpected files in intermediate directories

---

.goreleaser.yml
Dockerfile.goreleaser

The expected approach is that the binary built by goreleaser is added to the docker container.
The container on the docker hub is not yet version 0.12.0
Checklist
---------

Fix docker container setup for goreleaser

---

changelog/unreleased/pull-217
cmd/rest-server/main.go
mux.go

The --log option accepts "stdout", "stderr" as filenames. This prevents rest-server from opening these files, it simply writes the logs to the STDOUT or STDERR stream provided by the caller.
**BREAKING** in case the user really used "stdout", "stderr" to specify file names, you'll need to update your rest-server invocation to use "./stdout", "./stderr".
No.
Checklist
---------
Not in the manual, but in the options help

feat: allow logging to stdout, stderr

---

.goreleaser.yml

Setup multi-architecture docker containers in goreleaser. The configuration is unfortunately a lot of copy&paste with minimal modifications for which I couldn't find a way to reduce the duplication.
See #125
Checklist
---------

Setup multi-architecture docker containers in goreleaser

---

changelog/unreleased/issue-230
handlers.go
repo/repo.go

The warning should only be printed if fsync is _not_ supported and not the other way around.
TODO:
Fixes #230
Regressed in #199
Checklist
---------

Fix inverted condition for fsync warning

---

changelog/unreleased/issue-238
handlers_test.go
repo/repo.go

Previously "null" was returned, which does not match the REST backend specification.
Fixes #238
Checklist
---------

Return empty array if there are no objects to list

---

examples/systemd/rest-server.service

Improve security of rest-server.service by restricting network access.
This patch improves the overall security assessment score given by `systemd-analyze security rest-server.service` from "1.3 OK" to "0.6 SAFE" (when using systemd-analyze version 253)
* Remove `AF_INET AF_INET6` from RestrictAddressFamilies. Sockets originating from socket activation are not affected by the systemd directive RestrictAddressFamilies. See [systemd.exec](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) man page.
* Add `PrivateNetwork=yes` as recommended for socket-activated services in the [systemd.socket](https://www.freedesktop.org/software/systemd/man/systemd.socket.html) …

Improve security of systemd service rest-server.service by restricting network access

---

examples/systemd/rest-server.socket

Change the example rest-server.socket file to match the default port used by rest-server
Discussed, not really, but I've created #269
Checklist
---------
Will add a changelog file and check that the commit message matches the other commits if the changes are fine to be accepted

Update rest-server.socket with correct default rest-server port

---

changelog/unreleased/pull-273
cmd/rest-server/main.go
cmd/rest-server/main_test.go

This allows server listen resources to be cleaned up appropriately.
- changes app to run within a context, and cleans up the server when the context is done.
- wraps several global variables up within a wrapper object, which makes the app easier to write tests for
- add a test helper function to start a server, then run client tests against it when it's ready
- add several tests to ensure the server is cleaned up properly.
This is split from a different PR, PR #272.
Checklist
---------

fix: shutdown gracefully on TERM or INT signals

---

changelog/unreleased/pull-272
cmd/rest-server/listener_unix.go
cmd/rest-server/listener_unix_test.go

Enhancement: add support for unix socket listen
Refactor main for easier testing, graceful termination and be able to prin the listening port after startup.
Add tests for both TCP and Unix socket listening.
The change to add unix socket listening was pretty simple, but the PR got bit bigger then I made some refactors to `main.go` to make it easier for testing (by removing use of gloabl variables).
Yes. This is the `rest-server` part of https://github.com/restic/restic/issues/4287
(it also includes the tiny change I proposed in #271)
Checklist
---------

Enhancement: add support for unix socket listen

---

changelog/unreleased/pull-271
changelog/unreleased/pull-272
changelog/unreleased/pull-273

Polishes changelogs.
No.
Checklist
---------

doc: Polish unreleased changelogs

---

changelog/unreleased/pull-295
cmd/rest-server/main.go

Previously, rest-server did not output whether append only mode
was enabled or disabled when starting up. The status of private
repositories was however output.
Since private repositories and append only are two important
settings that are directly related to the security of the rest-server
instance, it seems prudent to also output the status of append only.
No, I was just missing it in the output when setting up a new rest-server
instance in append-only mode.
Checklist
---------

Output status of append only mode on startup

---

changelog/unreleased/issue-189
cmd/rest-server/main.go
handlers.go
repo/repo.go

The group-accessible-repos option will let filesystem group id be able to access files and dir within the restic repo 
Add a new option flag to enable group access to repo files
This is try two to enable #189 as discussed in #190 
I've followed @MichaelEischer suggestion to have group write access too when this option is enabled, but I don't like it.
Checklist
---------

Add group-accessible-repos option

---

examples/systemd/rest-server.service

document how to use group-accessible repos with systemd
Fixes https://github.com/restic/rest-server/issues/320
Follow up to https://github.com/restic/rest-server/pull/308
Checklist
---------
- ~~[ ] I have added tests for all code changes.~~
- ~~[ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE)).~~

document how to use group-accessible repos with systemd

---

docker/create_user
docker/delete_user

create_user script does not support passwords with spaces.
I found no Issues discussing this.
Checklist
---------

Support passwords with spaces in docker container

---

README.md
changelog/unreleased/pull-307
cmd/rest-server/main.go
cmd/rest-server/main_test.go
handlers.go
mux.go
mux_test.go

This change adds support for reverse-proxy-based authentication with private repositories.
It introduces the `--proxy-auth-username` flag, which allows users to specify the header name containing the username so that the server can handle the access on the specific repository.
In #174 it was discussed that proxy-based authentication in combination with private repositories requires a header containing the username. For maximum compatibility, the name of this header should be configurable.
Checklist
---------

Add support for proxy-based authentication

---

README.md
changelog/unreleased/pull-315
cmd/rest-server/main.go
handlers.go

With tls activated, the rest-server will provide insecure tls versions and insecure or broken tls cipher suits. This change configures the default settings in tls mode, sets a secure set of cipher suits (according to CIS NGINX Benchmark v2.1.0) and sets up TLSv1.2 as min version. It also adds a command line parameter to select a different version as min version.
The current version of the crypto.tls library also sets a small, secure set of cipher suits as default and limits the available TLS versions to 1.2 and 1.3. Earlier versions are also available but have to be explicitly enabled during compilation. …

Hardened tls cipher suits and added option for tls min version

---

.github/workflows/tests.yml
README.md
build.go
changelog/unreleased/pull-322
go.mod

Require Go 1.23 as older versions are no longer supported. The latest golang.org/x/ packages require Go 1.23.
No.
Checklist
---------

Bump minimum Go version to 1.23

---

changelog/unreleased/issue-189
changelog/unreleased/pull-295
changelog/unreleased/pull-307
changelog/unreleased/pull-315

Update changelogs for consistent style.
No.
Checklist
---------

Polish changelogs

---

changelog/unreleased/issue-318
docker/entrypoint.sh

When rest-server is started without a htpasswd file, it creates an empty file. Make this file not world readable.
Fixes https://github.com/restic/rest-server/issues/318
Checklist
---------

Limit htpasswd perms

---

README.md
changelog/unreleased/issue-189
examples/systemd/rest-server.service

Add more documentation on how to use the `--group-accessible-repos` option.
Question in the forum: https://forum.restic.net/t/rest-server-group-accessible-repos/9764
Checklist
---------
- ~~[ ] I have added tests for all code changes.~~
- ~~[ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (see [template](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE)).~~

Improve description of group-accessible option
