restic/rest-server

handlers.go
main.go

This PR adds the following changes:
* Allow deleting config files
* Directly write to the target file, with O_EXCL

Make rest-server compatible

---

handlers.go
handlers_test.go

This commit introduces the strict checks from net/http.Dir, which fixes the directory traversal issue reported in #22.
Closes #22

Fix directory traversal

---

README.md

The instructions for this server are easier to understand after reading the section about how it is to be used from restic. Like for example how the username/password is to be used.

Add a hint of how to make restic use this server.

---

README.md
handlers.go

Auto create data/ subdirs on demand

---

handlers.go
mux.go

Returns not only blob names, but also their sizes.
References:
https://github.com/restic/restic/issues/1567
https://github.com/restic/restic/pull/1571

Introduce ListBlobsV2()

---

README.md

Adds a missing piece from the previous PR (#52).

doc: Add --private-repos flag to README.md (#48)

---

.travis.yml
build.go
cmd/rest-server/main_test.go
handlers_test.go

This PR must fail until I push the next commit, which fixes the tests.

Fix tests on Travis

---

README.md
cmd/rest-server/main.go

I even tested it, and it still works! ;)

Rename --cpuprofile flag to --cpu-profile. (#53)

---

Makefile

the makefile should not depend on sudo

remove sudo from makefile

---

.travis.yml
changelog/0.9.7_2018-02-18/issue-53
changelog/CHANGELOG-GitHub.tmpl
changelog/CHANGELOG.tmpl
changelog/TEMPLATE
changelog/unreleased/issue-44
changelog/unreleased/issue-60

Add changelog generated by calens

---

handlers.go

Signed-off-by: Alexander Trost <galexrt@googlemail.com>
See issue #68.

Exclude /metrics path from private repos check

---

README.md

Prefer https:// links in the documentation

---

Dockerfile
changelog/unreleased/issue-119
docker/entrypoint.sh

Fixes #119, new configuration options broke `DISABLE_AUTHENTICATION`. This ensures backwards compatibility.
#119
Checklist
---------

Fix Docker configuration for DISABLE_AUTHENTICATION

---

changelog/unreleased/issue-148
examples/systemd/rest-server.service

The supplied systemd unit file places some basic security restrictions
on the rest service.  This patch enhances those, and improves the
overall security assessment score given by `systemd-analyze security`
from "8.3 EXPOSED" to "1.3 OK".
Closes #148
Security enhancement for users of systemd, by using additional systemd security features.
Closes #148
Checklist
---------
- [ ✓ ] I have enabled [maintainer edits for this PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fo …

Improve security of example systemd unit file

---

changelog/unreleased/issue-119
changelog/unreleased/issue-131
changelog/unreleased/issue-146
changelog/unreleased/issue-148
changelog/unreleased/pull-112
changelog/unreleased/pull-142
changelog/unreleased/pull-158
changelog/unreleased/pull-160

Reword a few changelog entries.
No.
Checklist
---------
- ~~[ ] I have added tests for all changes in this PR~~
- ~~[ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))~~
- ~~[ ] I have run `gofmt` on the code in all commits~~

Reword changelogs

---

repo/repo.go

`ioutil.TempFile` always creates files with permissions `0600`. Use a custom method to be able to honor the `FileMode` configured in `repo.go`. Note that this is not a user visible change as the option is not exposed anywhere.
See #166.
Checklist
---------
- ~~[ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))~~

Honour repo.FileMode permissions

---

examples/systemd/rest-server.service

Include #MemoryHigh=bytes, since this is the preferred way to handle memory according to https://www.man7.org/linux/man-pages/man5/systemd.resource-control.5.html
Just now, concurrently: https://github.com/restic/rest-server/issues/209
Closes #209  
Checklist
---------
Honestly this section has a lot I don't yet understand; i am hoping since my pull request is very small in an example file that I've done the right stuff. Hopefully this is helpful in some small way! Thanks for creating the software!

add MemoryHigh to systemd example

---

.github/workflows/tests.yml
changelog/unreleased/pull-217

Sync github CI changes from restic and add the changelog verification step.
No.
Checklist
---------
- ~~[ ] I have added tests for all changes in this PR~~
- ~~[ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))~~

Update CI configuration and verify changelog entries

---

changelog/TEMPLATE

See commit.
Checklist
---------

Update changelog template with changes from restic

---

.goreleaser.yml

If the changelog generation is disabled in goreleaser, this also ignores custom release notes passed in via the command line (see https://goreleaser.com/customization/changelog/). Thus keep the default changelog configuration.
No.
Checklist
---------
- ~~[ ] I have added tests for all changes in this PR~~
- ~~[ ] There's a new file in `changelog/unreleased/` that describes the changes for our users (template [here](https://github.com/restic/rest-server/blob/master/changelog/TEMPLATE))~~

Let goreleaser use custom release notes

---

.github/ISSUE_TEMPLATE/BUG.md
.github/ISSUE_TEMPLATE/FEATURE.md
.github/PULL_REQUEST_TEMPLATE.md

Use the more concise and polished issue and pull request templates from restic. These are minimally modified to better fit rest-server.
No.
Checklist
---------

Sync issue and pr templates with restic

---

.goreleaser.yml
Release.md
changelog/unreleased/issue-321

Create zip files for windows.
Fixes https://github.com/restic/rest-server/issues/321
Checklist
---------

Build zip files for windows release binaries

---

changelog/unreleased/issue-318
changelog/unreleased/pull-295
changelog/unreleased/pull-307
changelog/unreleased/pull-322

Minor adjustments to changelogs.
Nope.
Checklist
---------

Polish changelogs
